name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit and integration tests
        run: |
          ./gradlew test
          ./gradlew integrationTest

      - name: Build Docker image
        run: |
          docker build -t very-code-challenge:latest .

      # - name: Save Docker image as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: docker-image
      #     path: |
      #       $(docker save very-code-challenge:latest | gzip > very-code-challenge.tar.gz && echo very-code-challenge.tar.gz)